# Generated by Django 4.1.3 on 2022-11-14 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('cor', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='videos',
            name='categoria_id',
            field=models.IntegerField(default=1, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.categorias', verbose_name='')),
        ),
    ]
