# Generated by Django 4.1.3 on 2022-11-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_categorias_videos_categoria_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
